['Meta']
# Sample information
id = 'P033347'								# Unique dataset identifier.
description = 'Dasatinib in K562 R1 - MS3'				# Short description about the experiment.	
condition = 'Dasatinib'							# The condition that was tested. e.g. molecule name.
treatment_time = '30 min'						# treatment time.

['Experiment']
# Experiment information
experiments = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]				# The experiment ids within a experiments
doses = [100.0, 30.0, 10.0, 3.0, 1.0, 0.3, 0.1, 0.03, 0.01, 0.0]	# The doses corresponding to the channel indices
dose_scale = '1e-9'							# The scaling factor for the doses in scientific notation
dose_unit = 'M'								# The base unit of the doses
control_experiment = [10]						# [<id>] The experiment id(s) that are the control(s) to which ratios are calculated. If multiple controls exist, do [<id>, <id>, ..].
measurement_type= 'TMT'							# The measurement type <LFQ|TMT|DIA|OTHER>
data_type = 'PEPTIDE'							# The data type <PEPTIDE|PROTEIN|OTHER>
search_engine = 'MAXQUANT'						# The search engine <MAXQUANT|DIANN|OTHER>
search_engine_version = '1.6.3.10'					# The search engine version

['Paths']
# The paths needed for import. They must be relative to the toml files
input_file = './evidence.txt'						# Relative path to the imput file holding the data

['Processing']
# Paramters for the datanalysis pipeline
available_cores = 5							# <N> number of cores for parallelization
max_missing = 4								# <N> number of measured intensities that are allowed to be 0 per curve
imputation = true							# <true | false> impute missing values
normalization = true							# Median centric normalization

['F Statistic']
alpha = 0.05								# <0.0, 1.0> p_value limit for a statistically meaningful curve (SAM-Analysis)
fc_lim = 0.45								# Absolute Log2 Fold Change limit for a biologically meaningful curve (SAM-Analysis)
