# conda env create -f environment.yml
name: curve_curator
channels:
  - conda-forge
  - defaults
  - bokeh
dependencies:
  - bokeh=3.2
  - numpy
  - pandas
  - python=3.11
  - scipy
  - statsmodels
  - toml
  - tqdm
  - pytest