#
# In this file, you find all possible parameters. The assigned values are default values (if possible).
# It is more of a reference to what is maximal possible. We recommend using the minimal toml file as a starting point and then add parameters as you need them.
# Good luck with your analysis.
#
# Flo
#



#
# Sample meta information
#
['Meta']
id = 'ID1'								# Unique dataset identifier.
description = 'Some experiment'						# Short description about the experiment.	
condition = 'DrugX'							# The condition that was tested. e.g. molecule name.
treatment_time = '24 h'							# treatment time.


#
# Experiment information
#
['Experiment']
experiments = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]			# The experiment ids within an experiments. Can also be a list of strings ['A', 'B', 'C', ..].
doses = [0.0, 0.03, 0.3, 1.0, 3.0, 10.0, 30.0, 100.0, 300.0, 1000.0, 10000.0] # The doses corresponding to the channel indices.
dose_scale = '1e-9'							# The scaling factor for the doses in scientific notation.
dose_unit = 'M'								# The base unit of the doses.
control_experiment = [1]						# [<id>] The experiment id(s) that are the control(s) to which ratios are calculated. If multiple controls exist, do [<id>, <id>, ..].
measurement_type= 'OTHER'						# The measurement type <LFQ|TMT|DIA|OTHER>.
data_type = 'OTHER'							# The data type <PEPTIDE|PROTEIN|OTHER>.
search_engine = 'OTHER'							# The search engine <MAXQUANT|DIANN|PD|MSFRAGGER|OTHER>.
search_engine_version = 'X.X.X.X'					# The search engine version.


#
# The paths needed for import/export. They must be relative to the toml files
#
['Paths']
input_file = './evidence.txt'						# Relative path to the input file holding the data.
curves_file = './curves.txt'						# Relative path to the output file containing the curves.
decoys_file = './decoys.txt'						# Relative path to the output file containing the decoy curves.
fdr_file = './fdr.txt'							# Relative path to the file containing the fdr estimate in fdr mode.
normalization_file = './normalization_factors.txt'			# Relative path to the file containing the normalization_factor for each experiment.
mad_file = './mad.txt'							# Relative path to the file containing the mad analysis for each experiment.
dashboard = './dashboard.html'						# Relative path to the interactive dashboard to explore the curves.


#
# Parameters for the data preprocessing and cleaning prior to curve fitting
#
['Processing']
# Parameters for the data analysis pipeline
available_cores = 5							# <N> number of cores for parallelization.
max_missing = 11							# <N> number of measured intensities that are allowed to be missing per curve excluding controls.
max_imputation = 11							# <N> number of imputed intensities that are allowed per curve excluding controls.
imputation = false							# <true | false> If true, impute missing values.
normalization = false							# <true | false> If true, perform median centering of log-normalized values.
ratio_range = [0.0, +inf]						# [<lower>, <upper>] The range of values the response ratios can have. A value outside the range will be clipped to the lower or upper boundary value.


#
# Parameters to fine-tune the curve fitting procedure
#
['Curve Fit']
front = 1.0								# <N> This will fix the curve front to the value N. 
slope = 1.0								# <N> This will fix the curve slope to the value N.
back = 0.0								# <N> This will fix the curve back to the value N.
weights	 = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]	# Add weights for the curve fit. They must have the same order and number as doses and experiments. Not compatible with interpolation points.
interpolation = false							# <true | false> use interpolated helperpoints for the curve fit.
type = 'OLS'								# <'OLS'|'MLE'> The type of parameter estimation.
speed = 'standard'							# <'fast'|'standard'|'exhaustive'|'basinhopping'> The approach of finding the global minimum.
max_iterations = 1100							# <N> This will limit the number of iterations to N before parameter estimation is terminated.
control_fold_change = false						# <true | false> If true, the fold change is relative to the control. If false (default) it is the ratio of the model between the lowest and highest dose.
interpolation = false							# <true | false> Use interpolation helper points for robust curve fitting. Not compatible with point weights.


#
# Parameters to fine-tune the statistical evaluation
#
['F Statistic']
alpha = 0.05								# <0.0, 1.0> p_value limit for a statistically meaningful curve (SAM-Analysis).
fc_lim = 0.45								# Absolute Log2 Fold Change limit for a biologically meaningful curve (SAM-Analysis).
optimized_dofs = true							# <true | false> Use the optimized degrees of freedom for correct p-value estimation.
loc = 0.12								# <N> This will fix the location parameter of the f-distribution to the value N. 
scale = 1.0								# <N> This will fix the scale parameter of the f-distribution to the value N. 
dfn = 5.0								# <N> This will fix the dfn parameter of the f-distribution to the value N. 
dfd = 7.0								# <N> This will fix the dfd parameter of the f-distribution to the value N. 
quality_min = -inf							# <N> This will apply an extra intensity filter of N for regulated curves.  
mtc_method = 'sam'							# Multiple testing correction method. See statsmodel for available types. Default CurveCurator is the SAM-statistic.
not_rmse_limit = 0.1							# <N> specifies the root-mean-squared error threshold for the not classification.
not_p_limit = +inf							# <N> specifies an additional maximum p-value threshold for the not classification.
decoy_ratio = 1.0							# <N> specifies the target decoy ratio.


#
# Parameters to control dashboard properties
#
['Dashboard']
backend = 'svg'								# <'webgl'|'svg'|'canvas'> Specifies the HTML output backend. In svg mode, one can export .svg file for publication. webgl mode is for super fast interaction of big files.

