['Meta']
# Sample information
id = 'ID1'								# Unique dataset identifier.
description = 'Some expeirment'						# Short description about the experiment.	
condition = 'DrugX'							# The condition that was tested. e.g. molecule name.
treatment_time = '24 h'							# treatment time.

['Experiment']
# Experiment information
experiments = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]			# The experiment ids within a experiments
doses = [0.0, 0.03, 0.3, 1.0, 3.0, 10.0, 30.0, 100.0, 300.0, 1000.0, 10000.0] # The doses corresponding to the channel indices
dose_scale = '1e-9'							# The scaling factor for the doses in scientific notation
dose_unit = 'M'								# The base unit of the doses
control_experiment = 1							# <N> The index of the control channel to which ratios will be calculated


['Paths']
# The paths needed for import. They must be relative to the toml files
input_file = './evidence.txt'						# Relative path to the imput file holding the data


['Processing']
# Paramters for the datanalysis pipeline
curve_alpha = 0.05							# <0.0, 1.0> p_value limit for a statistically meaningful curve (SAM-Analysis)
curve_fclim = 0.45							# Absolute Log2 Fold Change limit for a biologically meaningful curve (SAM-Analysis)