['Meta']
# Sample information
id = 'ID1'								# Unique dataset identifier.
description = 'Some experiment with triplicates'			# Short description about the experiment.	
condition = 'DrugX'							# The condition that was tested. e.g. molecule name.
treatment_time = '24 h'							# treatment time.


['Experiment']
# Experiment information
experiments = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]	# The experiment ids within an experiments. Can also be a list of strings ['A', 'B', 'C', ..].
doses = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 10.0, 10.0, 10.0, 100.0, 100.0, 100.0, 1000.0, 1000.0, 1000.0, 10000.0, 10000.0, 10000.0] # The doses corresponding to the channel indices.
dose_scale = '1e-9'							# The scaling factor for the doses in scientific notation.
dose_unit = 'M'								# The base unit of the doses.
control_experiment = [1, 2, 3]						# [<id>] The experiment id(s) that are the control(s) to which ratios are calculated. If multiple controls exist, do [<id>, <id>, ..].


['Paths']
# The paths needed for import. They must be relative to the toml files
input_file = './input.txt'						# Relative path to the input file holding the data.


['Processing']
# Paramters for the datanalysis pipeline
curve_alpha = 0.05							# <0.0, 1.0> p_value limit for a statistically meaningful curve (SAM-Analysis).
curve_fclim = 0.45							# Absolute Log2 Fold Change limit for a biologically meaningful curve (SAM-Analysis).